insert into team values ('0', 'Natus Vincere', 'Ukraine')
insert into team values ('1', 'Cloud9', 'United States')
insert into team values ('2', 'Vitality', 'France')
insert into team values ('3', 'Astralis', 'Denmark')
insert into team values ('4', 'Spirit', 'Russia')
insert into team values ('5', 'G2', 'France')
insert into team values ('6', 'paiN', 'Brazil')
insert into team values ('7', 'ViCi', 'China')

insert into player values ('0', '2', 'ZywOo', 'France')
insert into player values ('1', '0', 's1mple', 'Ukraine')
insert into player values ('2', '4', 'w0nderful', 'Ukraine')
insert into player values ('3', '6', 'saffee', 'Brazil')
insert into player values ('4', '1', 'sh1ro', 'Russia')
insert into player values ('5', '5', 'm0NESY', 'Russia')
insert into player values ('6', '7', 'Kaze', 'Malaysia')
insert into player values ('7', '5', 'NiKo', 'Bosnia')

insert into statistic values ('0', '0', '1.28', '21.12.2021')
insert into statistic values ('1', '1', '1.25', '21.12.2021')
insert into statistic values ('2', '3', '1.24', '21.12.2021')
insert into statistic values ('3', '4', '1.22', '21.12.2021')
insert into statistic values ('4', '5', '1.21', '21.12.2021')
insert into statistic values ('5', '6', '1.20', '21.12.2021')
insert into statistic values ('6', '2', '1.18', '21.12.2021')
insert into statistic values ('7', '7', '1.15', '21.12.2021')